---
title: "Results by urban area and country"
author: "Michael D Garber"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: true
    toc_float: true
    toc_depth: 4
---

# By urban area
Ranked in descending order by age-standardized prevented mortality rate
```{r, eval=T, echo=F,warning=FALSE, message=F}
library(here)
library(tidyverse)
setwd(here("data-processed"))
load("hia_summary_gub.RData")

#people suggest DT for interactive tables
#https://stackoverflow.com/questions/27120002/is-it-possible-to-have-sortable-interactive-table-in-rmarkdown
#names(hia_summary_gub)
hia_summary_gub %>% 
  mutate(
      #Round these before passing through...will be easier than trying to round using data table
    #0 decimals is good.
      n_d_na_prev_std_who_per_100k_pop_pt_round=round(n_d_na_prev_std_who_per_100k_pop_pt),
      n_d_na_prev_std_who_per_100k_min_over_9_round=round(n_d_na_prev_std_who_per_100k_pop_min_over_9),
      n_d_na_prev_std_who_per_100k_max_over_9_round=round(n_d_na_prev_std_who_per_100k_pop_max_over_9)
  ) %>% 
  dplyr::select(
    city_name_admin_code_country_name,
    ends_with("round")
  ) %>% 
  arrange(desc(n_d_na_prev_std_who_per_100k_pop_pt_round)) %>% 
  #Note column names can be changed
#  https://rstudio.github.io/DT/
  DT::datatable(
    colnames = c(
      "Urban area name", 
      "Age-standardized non-accidental deaths prevented per 100k adults 30+",
      "Lower 95% uncertainty limit",
      "Upper 95% uncertainty limit")
    ) 
```

# By country
Ranked in descending order by age-standardized prevented mortality rate
```{r, eval=T, echo=F,warning=FALSE, message=F}
setwd(here("data-processed"))
load("hia_summary_country.RData")

#people suggest DT for interactive tables
#https://stackoverflow.com/questions/27120002/is-it-possible-to-have-sortable-interactive-table-in-rmarkdown
#names(hia_summary_gub)
hia_summary_country %>% 
    mutate(
        #Round these here as above
      n_d_na_prev_std_who_per_100k_pop_pt_round=round(n_d_na_prev_std_who_per_100k_pop_pt),
      n_d_na_prev_std_who_per_100k_min_over_9_round=round(n_d_na_prev_std_who_per_100k_pop_min_over_9),
      n_d_na_prev_std_who_per_100k_max_over_9_round=round(n_d_na_prev_std_who_per_100k_pop_max_over_9)
  ) %>% 
  dplyr::select(country_name_en, ends_with("round")) %>% 
  arrange(desc(n_d_na_prev_std_who_per_100k_pop_pt_round)) %>% 
  #Note you can change row names
#  https://rstudio.github.io/DT/
  DT::datatable(
    colnames = c(
      "Country name", 
       "Age-standardized non-accidental deaths prevented per 100k adults 30+",
      "Lower 95% uncertainty limit",
      "Upper 95% uncertainty limit")
    ) 
```